baseURL = '/'
title = 'DynaClassroom'
theme = 'dynaclassroom-hugo-theme'
defaultContentLanguage = 'es'

[markup.goldmark.renderer]
unsafe = true

[menus]
  [[menus.main]]
    name = 'Principal'
    pageRef = '/'
    weight = 10
  [[menus.main]]
    name = 'Blog'
    pageRef = '/blog'
    weight = 20
  [[menus.main]]
    name = 'Contacto'
    pageRef = '/contacto/contacto'
    weight = 30

  [[menus.footer]]
    name = 'TÃ©rminos de Uso'
    pageRef = '/terminos'
    weight = 10
  [[menus.footer]]
    name = 'Cookies'
    pageRef = '/cookies'
    weight = 20

[permalinks]
  thoughts = "/blog/:year/:month/:title/"

[taxonomies]
  tag = "tags"
  month = "months"
  author = "authors"

[params]
  googleTagManagerId = 'GTM-5ZCRJGMK'

  [params.home]
    videoUrl = "https://player.vimeo.com/video/1047791308?background=1&autoplay=1&loop=1&muted=1"
    claimBanner = "Transforma objetos del mundo real en herramientas interactivas de aprendizaje"
    description = "DynaClassroom es un **entorno de aprendizaje** para que estudiantes y docentes puedan **explorar cualquier idea juntos**, dotando de comportamiento computacional a los objetos del **mundo real**."


